Documentation and release prep
puppetlabs/puppetlabs-puppet_operations_appliance pull request #41
Opened 2021-01-14 15:38 UTC by MartyEwings

resolves #6

2021-01-14 16:00 UTC, jarretlavallee requested changes
Looks pretty good. I put in a few nit picks. You may also want to generate the REFERENCE.md. The code headers may need to be updated to account for it. 

```
pdk bundle exec rake strings:generate:reference
```

The REFERENCE.md will populate the reference page in the forge and generate docs around the code from the header comments with `puppet-strings.

2021-01-14 16:00 UTC, jarretlavallee commented on README.md
> +psql "sslmode=verify-ca sslrootcert=/etc/puppetlabs/puppet/ssl/certs/ca.pem  sslcert=/etc/puppetlabs/puppet/ssl/certs/<fqdn_rsan_host>.pem sslkey=/etc/puppetlabs/puppet/ssl/private_keys/<fqdn_rsan_ho
For copy/paste ability

```suggestion
psql "host=$(puppet config print server) port=5432 user=rsan sslmode=verify-full sslcert=$(puppet config print hostcert) sslkey=$(puppet config print hostprivkey) sslrootcert=$(puppet config print localcacert) dbname=<pe_db_name>"
```

2021-01-14 16:00 UTC, jarretlavallee commented on README.md
> + To workaround change the private key file to 0600 or less, Puppet will manage this file back to incorrect permissions, for long term access making a copy of the key with the correct permissions is t
Potential workaround: https://puppet.com/docs/puppet/7.1/config_file_main.html#special-types-of-values-for-settings

> Settings that take a single file or directory (like ssldir) can accept an optional hash of permissions. When starting up, Puppet enforces those permissions on the file or directory.

Perhaps we can set that for the `privatekeydir` or `hostprivkey` setting.

2021-01-14 16:00 UTC, jarretlavallee commented on README.md
> +Please refer to the documenation of Puppet Metrics collector for recommended work arounds
This would be the puppet metrics dashboard module for this deployment.

2021-01-14 16:00 UTC, jarretlavallee commented on README.md
> +<RSAN-ip\>:3000\
```suggestion
http://<RSAN-ip\>:3000\
```

2021-01-14 16:00 UTC, jarretlavallee commented on README.md
> + - derdanne/nfs (>= 2.1.5)
The formatting is inconsistent with these new ones.

```suggestion
- derdanne/nfs (>= 2.1.5)
```

2021-01-14 16:02 UTC, jarretlavallee commented on README.md
> + - derdanne/nfs (>= 2.1.5)
To solve the formatting issue, you may need to add the `  -` to these.

2021-01-14 16:02 UTC, MartyEwings commented on README.md
> +Please refer to the documenation of Puppet Metrics collector for recommended work arounds
doh

2021-01-14 16:05 UTC, jarretlavallee commented on README.md
> + - derdanne/nfs (>= 2.1.5)
Nevermind. It would just be one or the other. The unordered list works well.

2021-01-14 16:07 UTC, jarretlavallee commented on README.md
> +Please refer to the documenation of Puppet Metrics collector for recommended work arounds
```suggestion
Please refer to the documentation of (Puppet Metrics Dashboard](https://forge.puppet.com/modules/puppetlabs/puppet_metrics_dashboard) for recommended workarounds
```

2021-01-14 16:11 UTC, jarretlavallee commented
We should document resource requirements so the customer knows what size of a machine needs to be deployed for RSAN.

2021-01-14 16:11 UTC, jarretlavallee commented
Also, the agent OS needs to be the same OS as the master or it cannot deploy the client tools automatically.

2021-01-14 16:12 UTC, jarretlavallee commented on README.md
> + - All features are currently
Currently what?

2021-01-14 16:14 UTC, MartyEwings commented on README.md
> + - All features are currently
doh!

2021-01-14 16:16 UTC, jarretlavallee commented on README.md
> +**rsan::exporter::rsan_importer_ips**
This should show the syntax of setting this parameter or link to the REFERENCE.md for information.

In hiera"

```
rsan::exporter::rsan_importer_ips:
  - 1.2.3.4
 ```

In the class declaration or in the console the value would be an array

```
["1.2.3.4"]
```

2021-01-14 16:25 UTC, jarretlavallee reviewed
Minor formatting updates

2021-01-14 16:25 UTC, jarretlavallee commented on README.md
> +/var/pesupport/<FQDN of Infrastructure node\>/var/log\
```suggestion
`/var/pesupport/<FQDN of Infrastructure node\>/var/log\`
```

2021-01-14 16:25 UTC, jarretlavallee commented on README.md
> +/var/pesupport/<FQDN of Infrastructure node\>/opt/puppetlabs\
```suggestion
`/var/pesupport/<FQDN of Infrastructure node\>/opt/puppetlabs\`
```

2021-01-14 16:25 UTC, jarretlavallee commented on README.md
> +/var/pesupport/<FQDN of Infrastructure node\>/etc/puppetlabs
```suggestion
`/var/pesupport/<FQDN of Infrastructure node\>/etc/puppetlabs`
```

2021-01-14 16:25 UTC, jarretlavallee commented on README.md
> +http://<RSAN-ip\>:3000\
```suggestion
**URL:** http://<RSAN-ip\>:3000\
```

2021-01-14 16:25 UTC, jarretlavallee commented on README.md
> +User: admin\
```suggestion
**User:** admin\
```

2021-01-14 16:25 UTC, jarretlavallee commented on README.md
> +Password: admin
```suggestion
**Password:** admin
```

2021-01-14 16:25 UTC, jarretlavallee commented on README.md
> +The RSAN node will, by default, mount /var/log/ /opt/puppetlabs and /etc/puppetlabs from each of the Puppet Enterprise Infrastructure nodes on the RSAN platform in the following location, as read onl
```suggestion
The RSAN node will, by default, mount `/var/log/`, `/opt/puppetlabs` and `/etc/puppetlabs` from each of the Puppet Enterprise Infrastructure nodes on the RSAN platform in the following location, as read-only file systems.
```

2021-01-15 14:25 UTC, MartyEwings commented
> We should document resource requirements so the customer knows what size of a machine needs to be deployed for RSAN.

iv been testing on m1 medium, and that's probably as small as you want any Puppet agent, ill set that as minimum

2021-01-15 15:19 UTC, MartyEwings commented on README.md
> + To workaround change the private key file to 0600 or less, Puppet will manage this file back to incorrect permissions, for long term access making a copy of the key with the correct permissions is t
im going to see if i can resolve this in an issue

#40

2021-01-15 15:27 UTC, jarretlavallee commented on README.md
> +`/var/pesupport/<FQDN of Infrastructure node\>/var/log\`
My bad on these. They need to be an unordered list and remove the `\>` now that they are in the inline code.

```
* `/var/pesupport/<FQDN of Infrastructure node>/var/log`
```

2021-01-15 15:33 UTC, jarretlavallee commented on README.md
> +For imformation on executing PE tasks see the [Puppet Enterprise Documentation](https://puppet.com/docs/pe/2019.8/tasks_in_pe.html)\
```suggestion
For information on executing PE tasks see the [Puppet Enterprise Documentation](https://puppet.com/docs/pe/2019.8/tasks_in_pe.html)\
```

2021-01-15 16:23 UTC, jarretlavallee approved these changes
LGTM ship it

2021-01-15 16:24 UTC, merged