Fix #46
puppetlabs/puppetlabs-puppet_operations_appliance pull request #47
Opened 2021-04-26 09:21 UTC by MartyEwings

https://github.com/puppetlabs/RSAN/issues/46

Prior to this commit on some deployments of the exporter class on a postgres node, resource ordering meant that default postgres users and groups where selected instead of the puppet_enterprise defaults

2021-04-26 12:36 UTC, dylanratcliffe commented
@MartyEwings how have you acceptance tested this? I have a feeling that this could behave differently in the following scenarios:

* Classified with `rsan::exporter` using a node group
* Classified with `rsan::exporter` using static node declaration in site.pp

Sometimes it can be possible for custom classes to be evaluated before the `puppet_enterprise` code which can mean that doing things like this will fail

2021-04-26 12:36 UTC, dylanratcliffe reviewed
@MartyEwings how have you acceptance tested this? I have a feeling that this could behave differently in the following scenarios:

* Classified with `rsan::exporter` using a node group
* Classified with `rsan::exporter` using static node declaration in site.pp

Sometimes it can be possible for custom classes to be evaluated before the `puppet_enterprise` code which can mean that doing things like this will fail

2021-04-26 14:31 UTC, MartyEwings commented
It's been tested on a couple of installs on different versions, all node group based,  but thats how rsan is to be installed.

Problem was without this, it picks up the defaults from pe_postgres, which is wrong.

I could always define my own params but that seems redundant

2021-04-27 11:38 UTC, dylanratcliffe commented
IMO having a module make assumptions about how it's going to be classified is poor practice, people should be able to use node groups, existing roles/profiles, or any other method to classify the class and it should be able to work fine. Maybe the best compromise would be to expose these values as parameters on the class but have them default to what they are set to currently. That way if someone is doing something strange or custom, they can still get it working without a code change

2021-04-27 11:58 UTC, MartyEwings commented
> IMO having a module make assumptions about how it's going to be classified is poor practice, people should be able to use node groups, existing roles/profiles, or any other method to classify the class and it should be able to work fine. Maybe the best compromise would be to expose these values as parameters on the class but have them default to what they are set to currently. That way if someone is doing something strange or custom, they can still get it working without a code change

Sounds like a plan, ill push the changes

2021-04-27 12:36 UTC, MartyEwings commented
I decided to statically define some default params, the dynamic calls to PE was gonna cause more problems that it hoped to solve

2021-04-27 12:49 UTC, dylanratcliffe requested changes

2021-04-27 12:49 UTC, dylanratcliffe commented on manifests/exporter.pp
> +  Optional[String] $pg_user =  'pe-postgres',
```suggestion
  Optional[String] $pg_user = 'pe-postgres',
```

2021-04-27 12:49 UTC, dylanratcliffe commented on manifests/exporter.pp
> +  Optional[String] $pg_user =  'pe-postgres',
![](https://media2.giphy.com/media/MHCY3HK7g41wY/giphy.gif?cid=e1bb72fflvypgue2128razgts5dmn1rwcr7iivla3p6c5q1a&rid=giphy.gif&ct=g)

2021-04-27 13:42 UTC, dylanratcliffe approved these changes

2021-04-27 14:19 UTC, merged